binding:
  port: 4545
  host : 127.0.0.1
source: file # file or database
database:
  url: http:/127.0.0.1:8123
  username: simulator_app
  password: "your_password"
tracking:
  enabled: false
log_level: info
channel_capacity: 10000